module InventoryLocators
  ADD_TO_CART_BUTTON = 'button.btn_primary.btn_inventory'
  REMOVE_BUTTON = 'button.btn_secondary.btn_inventory'
  CART_REMOVE_BUTTON = 'button.cart_button'
  BACK_TO_SHOPPING = 'button.back'
  ITEM_PRICE = 'div.inventory_item_price'
  CART_BUTTON = 'a.shopping_cart_link'
  CART_BADGE = 'span.shopping_cart_badge'
  CHECKOUT_BUTTON = 'button.btn_action.checkout_button'
  CHECKOUT_FIRST_NAME = 'input#first-name'
  CHECKOUT_LAST_NAME = 'input#last-name'
  CHECKOUT_ZIP_CODE = 'input#postal-code'
  CHECKOUT_CONTINUE_BUTTON = 'input.btn_primary.cart_button'
  CHECKOUT_FINISH_BUTTON = 'button#finish'
  SORT_DROPDOWN = '.right_component'
  SORT_DROPDOWN_ACTIVE = 'span.active-option'
  SORT_OPTIONS = 'select.product_sort_container'
  SORT_OPTION_1 = '#header_container > div.header_secondary_container > div > span > select > option:nth-child(1)'
  SORT_OPTION_2 = '#header_container > div.header_secondary_container > div > span > select > option:nth-child(2)'
  SORT_OPTION_3 = '#header_container > div.header_secondary_container > div > span > select > option:nth-child(3)'
  SORT_OPTION_4 = '#header_container > div.header_secondary_container > div > span > select > option:nth-child(4)'
end
